import { PackageItem, ServiceItem, FAQItem, AnnouncementItem, WebsiteSettings } from '../types';

export const BRAND = {
  OFFICIAL_NAME: 'JOSH RAMBO BDIX Bypass™',
  SHORT_NAME: 'JOSH RAMBO',
  TAGLINE: 'Faster Bangladesh Together',
  CATEGORY: 'BDIX Bypass / Networking Service',
  PRIMARY_STATEMENT: 'দীর্ঘ ৩ বছরের বেশি সময় সফলতার সাথে BDIX বাইপাস প্রোভাইড করে যাচ্ছি।',
  SUPPORTING_MESSAGE: 'Bufferless experience এর জন্য JOSH RAMBO BDIX Bypass™-এর সাথে যোগাযোগ করুন।',
  COPYRIGHT: '© 2026 JOSH RAMBO BDIX Bypass™. All rights reserved.',
} as const;

export const DEFAULT_CONTACTS = {
  TELEGRAM_PERSONAL: 'https://t.me/joshvhai',
  TELEGRAM_USERNAME: '@joshvhai',
  TELEGRAM_GROUP: 'https://t.me/josharmy007',
  FACEBOOK_MESSENGER: 'https://www.fb.com/joshrambo007',
} as const;

export const DEFAULT_SETTINGS: WebsiteSettings = {
  brand_name: 'JOSH RAMBO BDIX Bypass™',
  short_brand_name: 'JOSH RAMBO',
  tagline: 'Faster Bangladesh Together',
  hero_title: 'দীর্ঘ ৩ বছরের বেশি সময় সফলতার সাথে BDIX বাইপাস প্রোভাইড করে যাচ্ছি।',
  hero_description: 'Bufferless experience এর জন্য JOSH RAMBO BDIX Bypass™-এর সাথে যোগাযোগ করুন। উচ্চগতির স্টেবল কানেক্টিভিটি এবং অপ্টিমাইজড রাউটিং।',
  about_text: 'দীর্ঘ ৩ বছরের বেশি সময় ধরে JOSH RAMBO BDIX Bypass™ BDIX Bypass connectivity এবং networking experience নিয়ে কাজ করে আসছে। আমাদের লক্ষ্য হলো ব্যবহারকারীদের জন্য একটি stable, smooth এবং better streaming experience তৈরি করা।',
  support_text: 'সরাসরি সাপোর্ট ও সার্ভিসের বিস্তারিত তথ্যের জন্য আমাদের অফিশিয়াল টেলিগ্রাম বা মেসেঞ্জারে যোগাযোগ করুন।',
  telegram_url: DEFAULT_CONTACTS.TELEGRAM_PERSONAL,
  telegram_username: DEFAULT_CONTACTS.TELEGRAM_USERNAME,
  telegram_group_url: DEFAULT_CONTACTS.TELEGRAM_GROUP,
  facebook_url: DEFAULT_CONTACTS.FACEBOOK_MESSENGER,
  footer_text: 'দীর্ঘ ৩ বছরের বেশি সময় সফলতার সাথে BDIX বাইপাস প্রোভাইড করে যাচ্ছি। Faster Bangladesh Together.',
};

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    title: 'BDIX Bypass',
    description: 'Reliable BDIX Bypass connectivity for a smoother online experience.',
    icon: 'Network',
    status: 'active',
    sort_order: 1,
  },
  {
    id: 'srv-2',
    title: 'Streaming Optimized',
    description: 'Optimized connectivity for better streaming and reduced buffering.',
    icon: 'PlayCircle',
    status: 'active',
    sort_order: 2,
  },
  {
    id: 'srv-3',
    title: 'Network Optimization',
    description: 'Smart routing and connectivity optimization for improved performance.',
    icon: 'Cpu',
    status: 'active',
    sort_order: 3,
  },
  {
    id: 'srv-4',
    title: 'Stable Connectivity',
    description: 'Focus on consistent and reliable network performance.',
    icon: 'ShieldCheck',
    status: 'active',
    sort_order: 4,
  },
  {
    id: 'srv-5',
    title: 'Technical Support',
    description: 'Direct support through our official communication channels.',
    icon: 'Headphones',
    status: 'active',
    sort_order: 5,
  },
  {
    id: 'srv-6',
    title: 'Custom Solution',
    description: 'Networking solutions based on individual requirements.',
    icon: 'Settings2',
    status: 'active',
    sort_order: 6,
  },
];

export const INITIAL_PACKAGES: PackageItem[] = [
  {
    id: 'pkg-sky',
    name: 'SKY',
    internet_speed: '30 Mbps',
    service_speed: '3.75 Mbps',
    price: '75',
    duration: '24 Hours',
    description: 'দৈনন্দিন ব্রাউজিং ও এন্ট্রি-লেভেল BDIX বাইপাস কানেক্টিভিটি।',
    features: [
      'YouTube 30 Mbps',
      'Facebook 30 Mbps',
      'Steam / Epic ETC 30 Mbps',
      'BDIX / Streaming 3.75 Mbps',
      'Bufferless Experience',
      'Standard Telegram Support',
    ],
    badge: 'Starter',
    status: 'active',
    sort_order: 1,
  },
  {
    id: 'pkg-moon',
    name: 'MOON',
    internet_speed: '40 Mbps',
    service_speed: '5.00 Mbps',
    price: '90',
    duration: '24 Hours',
    description: 'সোশ্যাল মিডিয়া ও স্মুথ ভিডিও স্ট্রিমিংয়ের জন্য উপযুক্ত প্যাকেজ।',
    features: [
      'YouTube 40 Mbps',
      'Facebook 40 Mbps',
      'Steam / Epic ETC 40 Mbps',
      'BDIX / Streaming 5.00 Mbps',
      'Low Jitter & Latency',
      'Direct Telegram Support',
    ],
    badge: 'Standard',
    status: 'active',
    sort_order: 2,
  },
  {
    id: 'pkg-sun',
    name: 'SUN',
    internet_speed: '50 Mbps',
    service_speed: '6.25 Mbps',
    price: '110',
    duration: '24 Hours',
    description: 'দিনভর নিরবচ্ছিন্ন ব্রাউজিং ও লাইট এইচডি স্ট্রিমিং নিশ্চয়তা।',
    features: [
      'YouTube 50 Mbps',
      'Facebook 50 Mbps',
      'Steam / Epic ETC 50 Mbps',
      'BDIX / Streaming 6.25 Mbps',
      'Bufferless HD Streaming',
      'Fast CDN Routing Acceleration',
    ],
    badge: 'Popular',
    status: 'active',
    sort_order: 3,
  },
  {
    id: 'pkg-world',
    name: 'WORLD',
    internet_speed: '100 Mbps',
    service_speed: '12.5 Mbps',
    price: '170',
    duration: '24 Hours',
    description: 'আন্তর্জাতিক ও লোকাল কন্টেন্টে ব্যালেন্সড গ্লোবাল রাউটিং।',
    features: [
      'YouTube 100 Mbps',
      'Facebook 100 Mbps',
      'Steam / Epic ETC 100 Mbps',
      'BDIX / Streaming 12.5 Mbps',
      'Global Route Balancing',
      'Multi-Server Failover Support',
    ],
    badge: 'Recommended',
    status: 'active',
    sort_order: 4,
  },
  {
    id: 'pkg-sonic',
    name: 'SONIC',
    internet_speed: '20 Mbps',
    service_speed: '2.50 Mbps',
    price: '80',
    duration: '24 Hours',
    description: 'হাই-স্পিড টার্বো ট্রাফিক ও বাফারলেস মাল্টিমিডিয়া অভিজ্ঞতা।',
    features: [
      'YouTube 20 Mbps',
      'Facebook 20 Mbps',
      'Steam / Epic ETC 20 Mbps',
      'BDIX / Streaming 2.50 Mbps',
      'Sonic Speed Acceleration',
      'Low Latency Optimization',
    ],
    badge: 'Turbo',
    status: 'active',
    sort_order: 5,
  },
  {
    id: 'pkg-light',
    name: 'LIGHT',
    internet_speed: '30 Mbps',
    service_speed: '3.75 Mbps',
    price: '110',
    duration: '24 Hours',
    description: 'আল্ট্রা-লাইট প্যাকেট রাউটিং ও স্মুথ গেমিং/স্ট্রিমিং পারফরম্যান্স।',
    features: [
      'YouTube 30 Mbps',
      'Facebook 30 Mbps',
      'Steam / Epic ETC 30 Mbps',
      'BDIX / Streaming 3.75 Mbps',
      'Ultra Low Ping & Jitter',
      'Dedicated Routing Nodes',
    ],
    badge: 'Pro Gamer',
    status: 'active',
    sort_order: 6,
  },
  {
    id: 'pkg-motion',
    name: 'MOTION',
    internet_speed: '50 Mbps',
    service_speed: '6.25 Mbps',
    price: '150',
    duration: '24 Hours',
    description: 'ডাইনামিক ট্রাফিক ম্যানেজমেন্ট এবং 4K আল্ট্রা এইচডি স্ট্রিমিং।',
    features: [
      'YouTube 50 Mbps',
      'Facebook 50 Mbps',
      'Steam / Epic ETC 50 Mbps',
      'BDIX / Streaming 6.25 Mbps',
      'Dynamic Traffic Steering',
      'High Bandwidth Optimization',
    ],
    badge: 'High Performance',
    status: 'active',
    sort_order: 7,
  },
  {
    id: 'pkg-s25-ultra',
    name: 'S25 ULTRA',
    internet_speed: '100 Mbps',
    service_speed: '12.5 Mbps',
    price: '240',
    duration: '24 Hours',
    description: 'সর্বোচ্চ ফ্ল্যাগশিপ পারফরম্যান্স, ডেডিকেটেড ভিআইপি রাউটিং ও সাপোর্ট।',
    features: [
      'YouTube 100 Mbps',
      'Facebook 100 Mbps',
      'Steam / Epic ETC 100 Mbps',
      'BDIX / Streaming 12.5 Mbps',
      'Flagship Ultra Dedicated Line',
      'Zero Buffering Guarantee',
    ],
    badge: 'Flagship',
    status: 'active',
    sort_order: 8,
  },
];

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'BDIX Bypass কী?',
    answer: 'BDIX Bypass হলো একটি নেটওয়ার্কিং টেকনোলজি যার মাধ্যমে লোকাল ও ইন্টারন্যাশনাল ট্রাফিক অপ্টিমাইজড রুটে রিডাইরেক্ট করে নির্ভরযোগ্য এবং স্মুথ কানেক্টিভিটি নিশ্চিত করা হয়। এর ফলে স্ট্রিমিং ও কনটেন্ট এক্সেসে বাফারিং অনেকাংশে হ্রাস পায়।',
    status: 'active',
    sort_order: 1,
  },
  {
    id: 'faq-2',
    question: 'JOSH RAMBO BDIX Bypass™ কতদিন ধরে সার্ভিস দিচ্ছে?',
    answer: 'দীর্ঘ ৩ বছরের বেশি সময় সফলতার সাথে আমরা BDIX বাইপাস প্রোভাইড করে আসছি এবং গ্রাহকদের নির্ভরযোগ্য কানেক্টিভিটি অভিজ্ঞতা দিয়ে যাচ্ছি।',
    status: 'active',
    sort_order: 2,
  },
  {
    id: 'faq-3',
    question: 'কিভাবে সার্ভিস নিতে পারি?',
    answer: 'সার্ভিস নেওয়ার জন্য আমাদের অফিসিয়াল টেলিগ্রাম (@joshvhai) বা ফেসবুক মেসেঞ্জারে সরাসরি নক দিন। আমাদের টিম আপনাকে উপযুক্ত প্যাকেজ সিলেক্ট এবং দ্রুত সেটআপ করতে সাহায্য করবে।',
    status: 'active',
    sort_order: 3,
  },
  {
    id: 'faq-4',
    question: 'কিভাবে Support পাবো?',
    answer: 'আমাদের প্রধান সাপোর্ট চ্যানেল হলো টেলিগ্রাম পার্সোনাল চ্যাট ও টেলিগ্রাম গ্রুপ (t.me/josharmy007)। যেকোনো টেকনিক্যাল বা কানেকশন সংক্রান্ত সমস্যায় সরাসরি মেসেজ দিলেই দ্রুত সহায়তা পাবেন।',
    status: 'active',
    sort_order: 4,
  },
  {
    id: 'faq-5',
    question: 'কোন নেটওয়ার্কে ব্যবহার করা যাবে?',
    answer: 'বাংলাদেশের যেকোনো স্ট্যান্ডার্ড ব্রডব্যান্ড আইএসপি এবং মোবাইল ডাটা নেটওয়ার্কে আমাদের BDIX Bypass সেবাটি কনফিগার করে ব্যবহার করা সম্ভব। বিস্তারিত কনফিগারেশন গাইডের জন্য যোগাযোগ করুন।',
    status: 'active',
    sort_order: 5,
  },
];

export const INITIAL_ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: 'ann-1',
    title: 'অফিসিয়াল যোগাযোগ চ্যানেল',
    message: 'JOSH RAMBO BDIX Bypass™ সংক্রান্ত সব তথ্যের জন্য কেবল আমাদের ভেরিফাইড টেলিগ্রাম (@joshvhai) এবং গ্রুপে যোগাযোগ করুন।',
    type: 'info',
    status: 'active',
    start_date: new Date().toISOString(),
    sort_order: 1,
  },
];
